# frozen_string_literal: true

$LOAD_PATH.push File.expand_path('lib', __dir__)

Gem::Specification.new do |s|
  s.name        = 'dub'
  s.version     = '0.12.3'
  s.platform    = Gem::Platform::RUBY
  s.licenses    = ['Apache-2.0']
  s.summary     = ''
  s.homepage    = 'https://github.com/dubinc/dub-ruby.git'
  s.description = 'Ruby Client SDK Generated by Speakeasy'
  s.authors     = ['Dub']
  s.metadata    = {
    'homepage_uri' => 'https://github.com/dubinc/dub-ruby.git',
    'documentation_uri' => 'https://github.com/dubinc/dub-ruby.git',
    'source_code_uri' => 'https://github.com/dubinc/dub-ruby.git'
  }

  s.files         = Dir['{lib,test}/**/*']
  s.require_paths = ['lib']
  s.required_ruby_version = '>= 3.2'

  s.add_dependency('base64', '>= 0.2.0', '< 1.0')
  s.add_dependency('faraday')
  s.add_dependency('faraday-multipart', '~> 1.2.0')
  s.add_dependency('faraday-retry', '~> 2.4.0')
  s.add_dependency('janeway-jsonpath', '~> 0.6.0')
  s.add_dependency('sorbet-runtime', '~> 0.6.12872')
  s.add_development_dependency('irb')
  s.add_development_dependency('minitest', '>= 5.27.0')
  s.add_development_dependency('minitest-focus', '~> 1.4.1')
  s.add_development_dependency('rake')
  s.add_development_dependency('rubocop', '~> 1.73.2')
  s.add_development_dependency('rubocop-minitest', '~> 0.37.1')
  s.add_development_dependency('sorbet', '~> 0.6.12872')
  s.add_development_dependency('tapioca', '~> 0.17.10')
  s.add_development_dependency('tsort', '~> 0.2.0')
end
