workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-first-source:
        inputs:
            - location: https://api.dub.co
        registry:
            location: registry.speakeasyapi.dev/dub/dub/my-first-source
targets:
    my-first-target:
        target: ruby
        source: my-first-source
        publish:
            rubygems:
                token: $rubygems_auth_token
