# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Click < ::Crystalline::FieldAugmented
      extend T::Sig


      field :browser, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('browser') } }

      field :city, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('city') } }

      field :continent, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('continent') } }

      field :country, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('country') } }

      field :device, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('device') } }

      field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id') } }

      field :ip, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('ip') } }

      field :os, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('os') } }

      field :referer, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('referer') } }

      field :referer_url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('refererUrl') } }

      field :region, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('region') } }

      field :timestamp, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('timestamp') } }

      field :url, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('url') } }

      field :qr, T.nilable(T::Boolean), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('qr') } }


      sig { params(browser: ::String, city: ::String, continent: ::String, country: ::String, device: ::String, id: ::String, ip: ::String, os: ::String, referer: ::String, referer_url: ::String, region: ::String, timestamp: ::String, url: ::String, qr: T.nilable(T::Boolean)).void }
      def initialize(browser: nil, city: nil, continent: nil, country: nil, device: nil, id: nil, ip: nil, os: nil, referer: nil, referer_url: nil, region: nil, timestamp: nil, url: nil, qr: nil)
        @browser = browser
        @city = city
        @continent = continent
        @country = country
        @device = device
        @id = id
        @ip = ip
        @os = os
        @referer = referer
        @referer_url = referer_url
        @region = region
        @timestamp = timestamp
        @url = url
        @qr = qr
      end
    end
  end
end
