# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # Code - A short code indicating the error code returned.
    class Code < T::Enum
      enums do
        BAD_REQUEST = new('bad_request')
      end
    end
  end
end
