# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # ConflictCode - A short code indicating the error code returned.
    class ConflictCode < T::Enum
      enums do
        CONFLICT = new('conflict')
      end
    end

  end
end
