# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  

    class Event < T::Enum
      enums do
        CLICK = new('click')
      end
    end
  end
end
