# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
      # LinkTagSchemaColor - The color of the tag.
      class LinkTagSchemaColor < T::Enum


        enums do
          RED = new('red')
          YELLOW = new('yellow')
          GREEN = new('green')
          BLUE = new('blue')
          PURPLE = new('purple')
          BROWN = new('brown')
          PINK = new('pink')
        end
      end
    end
  end
end
