# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared
    

      class PartnerApplicationSubmittedEventData
        extend T::Sig
        include Crystalline::MetadataFields


        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }

        field :created_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('createdAt'), required: true } }

        field :partner, Models::Shared::PartnerApplicationSubmittedEventPartner, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('partner'), required: true } }

        field :application_form_data, Crystalline::Nilable.new(Crystalline::Array.new(Models::Shared::ApplicationFormData)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('applicationFormData'), required: true } }

        sig { params(id: ::String, created_at: ::String, partner: Models::Shared::PartnerApplicationSubmittedEventPartner, application_form_data: T.nilable(T::Array[Models::Shared::ApplicationFormData])).void }
        def initialize(id:, created_at:, partner:, application_form_data: nil)
          @id = id
          @created_at = created_at
          @partner = partner
          @application_form_data = application_form_data
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @created_at == other.created_at
          return false unless @partner == other.partner
          return false unless @application_form_data == other.application_form_data
          true
        end
      end
    end
  end
end
