# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class PartnerEnrolledEventFieldsDataReferralFormData5Type < T::Enum
        enums do
          DATE = new('date')
        end
      end
    end
  end
end
