# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Shared

      class Provider < T::Enum
        enums do
          STRIPE = new('stripe')
          SHOPIFY = new('shopify')
          CUSTOM = new('custom')
        end
      end
    end
  end
end
