# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Shared
  
    # The user has sent too many requests in a given amount of time ("rate limiting")
    class RateLimitExceeded < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig


      field :error, ::OpenApiSDK::Shared::RateLimitExceededError, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('error') } }


      sig { params(error: ::OpenApiSDK::Shared::RateLimitExceededError).void }
      def initialize(error: nil)
        @error = error
      end
    end
  end
end
