# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # ApproveBountySubmissionStatus - The status of the submission
      class ApproveBountySubmissionStatus < T::Enum
        enums do
          DRAFT = new('draft')
          SUBMITTED = new('submitted')
          APPROVED = new('approved')
          REJECTED = new('rejected')
        end
      end
    end
  end
end
