# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ApprovePartnerApplicationRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the partner to approve.
        field :partner_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('partnerId'), required: true } }
        # The ID of the group to assign the partner to. If not provided, the partner will be assigned to the group they applied to, or the program's default group if no application group is set.
        field :group_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('groupId') } }

        sig { params(partner_id: ::String, group_id: T.nilable(::String)).void }
        def initialize(partner_id:, group_id: nil)
          @partner_id = partner_id
          @group_id = group_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @partner_id == other.partner_id
          return false unless @group_id == other.group_id
          true
        end
      end
    end
  end
end
