# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class BanPartnerRequestBody
        extend T::Sig
        include Crystalline::MetadataFields


        field :reason, Models::Operations::Reason, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('reason'), required: true, 'decoder': Utils.enum_from_string(Models::Operations::Reason, false) } }
        # The ID of the partner to create a link for. Will take precedence over `tenantId` if provided.
        field :partner_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('partnerId') } }
        # The ID of the partner in your system. If both `partnerId` and `tenantId` are not provided, an error will be thrown.
        field :tenant_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tenantId') } }

        sig { params(reason: Models::Operations::Reason, partner_id: T.nilable(::String), tenant_id: T.nilable(::String)).void }
        def initialize(reason:, partner_id: nil, tenant_id: nil)
          @reason = reason
          @partner_id = partner_id
          @tenant_id = tenant_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @reason == other.reason
          return false unless @partner_id == other.partner_id
          return false unless @tenant_id == other.tenant_id
          true
        end
      end
    end
  end
end
