# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class BulkUpdateLinksRequestBody < ::Crystalline::FieldAugmented
      extend T::Sig


      field :data, ::OpenApiSDK::Operations::Data, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('data') } }
      # The external IDs of the links to update as stored in your database.
      field :external_ids, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('externalIds') } }
      # The IDs of the links to update. Takes precedence over `externalIds`.
      field :link_ids, T.nilable(T::Array[::String]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('linkIds') } }


      sig { params(data: ::OpenApiSDK::Operations::Data, external_ids: T.nilable(T::Array[::String]), link_ids: T.nilable(T::Array[::String])).void }
      def initialize(data: nil, external_ids: nil, link_ids: nil)
        @data = data
        @external_ids = external_ids
        @link_ids = link_ids
      end
    end
  end
end
