# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # BulkUpdateCommissionsStatus - The status to apply to every commission in the batch.
      class BulkUpdateCommissionsStatus < T::Enum
        enums do
          PENDING = new('pending')
          REFUNDED = new('refunded')
          DUPLICATE = new('duplicate')
          CANCELED = new('canceled')
          FRAUD = new('fraud')
        end
      end
    end
  end
end
