# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    
      # CreatePartnerStatus - The status of the partner's enrollment in the program.
      class CreatePartnerStatus < T::Enum


        enums do
          PENDING = new('pending')
          APPROVED = new('approved')
          REJECTED = new('rejected')
          INVITED = new('invited')
          DECLINED = new('declined')
          DEACTIVATED = new('deactivated')
          BANNED = new('banned')
          ARCHIVED = new('archived')
        end
      end
    end
  end
end
