# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class CreatePartnerFieldsPartnersResponse201ApplicationJSONResponseBodyReferralFormDataType < T::Enum
        enums do
          NUMBER = new('number')
        end
      end
    end
  end
end
