# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # The deactivated partner
      class DeactivatePartnerResponseBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The ID of the deactivated partner.
        field :partner_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('partnerId'), required: true } }

        sig { params(partner_id: ::String).void }
        def initialize(partner_id:)
          @partner_id = partner_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @partner_id == other.partner_id
          true
        end
      end
    end
  end
end
