# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class Four < T::Enum


        enums do
          FOLDER_ID = new('folderId')
        end
      end
    end
  end
end
