# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class GetMetatagsRequest < ::Crystalline::FieldAugmented
      extend T::Sig

      # The URL to retrieve metatags for.
      field :url, ::String, { 'query_param': { 'field_name': 'url', 'style': 'form', 'explode': true } }


      sig { params(url: ::String).void }
      def initialize(url: nil)
        @url = url
      end
    end
  end
end
