# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    
      # GetTagsQueryParamSortOrder - The order to sort the tags by.
      class GetTagsQueryParamSortOrder < T::Enum


        enums do
          ASC = new('asc')
          DESC = new('desc')
        end
      end
    end
  end
end
