# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # GroupBy - The parameter to group the analytics data points by. Defaults to 'count' if undefined.
    class GroupBy < T::Enum
      enums do
        COUNT = new('count')
        TIMESERIES = new('timeseries')
        COUNTRIES = new('countries')
        CITIES = new('cities')
        DEVICES = new('devices')
        BROWSERS = new('browsers')
        OS = new('os')
        REFERERS = new('referers')
        TOP_LINKS = new('top_links')
        TOP_URLS = new('top_urls')
        TRIGGER = new('trigger')
      end
    end

  end
end
