# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # The lead event object to associate the commission with.
      class Lead
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the lead event to track. If not provided, defaults to 'Sign up'.
        field :event_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('eventName') } }
        # Additional metadata to be stored with the lead event. Max 10,000 characters.
        field :metadata, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::Object)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }

        sig { params(event_name: T.nilable(::String), metadata: T.nilable(T::Hash[Symbol, ::Object])).void }
        def initialize(event_name: nil, metadata: nil)
          @event_name = event_name
          @metadata = metadata
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @event_name == other.event_name
          return false unless @metadata == other.metadata
          true
        end
      end
    end
  end
end
