# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ListProgramApplicationsType < T::Enum
        enums do
          WEBSITE = new('website')
          YOUTUBE = new('youtube')
          TWITTER = new('twitter')
          LINKEDIN = new('linkedin')
          INSTAGRAM = new('instagram')
          TIKTOK = new('tiktok')
        end
      end
    end
  end
end
