# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ListPayoutsRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Filter the list of payouts by their corresponding status.
        field :status, Crystalline::Nilable.new(Models::Operations::ListPayoutsQueryParamStatus), { 'query_param': { 'field_name': 'status', 'style': 'form', 'explode': true } }
        # Filter the list of payouts by the associated partner. When specified, takes precedence over `tenantId`.
        field :partner_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'partnerId', 'style': 'form', 'explode': true } }
        # Filter the list of payouts by the associated partner's `tenantId` (their unique ID within your database).
        field :tenant_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'tenantId', 'style': 'form', 'explode': true } }
        # Filter the list of payouts by invoice ID (the unique ID of the invoice you receive for each batch payout you process on Dub). Pending payouts will not have an invoice ID.
        field :invoice_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'invoiceId', 'style': 'form', 'explode': true } }
        # The field to sort the list of payouts by.
        field :sort_by, Crystalline::Nilable.new(Models::Operations::ListPayoutsQueryParamSortBy), { 'query_param': { 'field_name': 'sortBy', 'style': 'form', 'explode': true } }
        # The sort order for the list of payouts.
        field :sort_order, Crystalline::Nilable.new(Models::Operations::ListPayoutsQueryParamSortOrder), { 'query_param': { 'field_name': 'sortOrder', 'style': 'form', 'explode': true } }
        # The page number for pagination.
        field :page, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
        # The number of items per page.
        field :page_size, Crystalline::Nilable.new(::Float), { 'query_param': { 'field_name': 'pageSize', 'style': 'form', 'explode': true } }

        sig { params(status: T.nilable(Models::Operations::ListPayoutsQueryParamStatus), partner_id: T.nilable(::String), tenant_id: T.nilable(::String), invoice_id: T.nilable(::String), sort_by: T.nilable(Models::Operations::ListPayoutsQueryParamSortBy), sort_order: T.nilable(Models::Operations::ListPayoutsQueryParamSortOrder), page: T.nilable(::Float), page_size: T.nilable(::Float)).void }
        def initialize(status: nil, partner_id: nil, tenant_id: nil, invoice_id: nil, sort_by: Models::Operations::ListPayoutsQueryParamSortBy::AMOUNT, sort_order: Models::Operations::ListPayoutsQueryParamSortOrder::DESC, page: 1.0, page_size: 100.0)
          @status = status
          @partner_id = partner_id
          @tenant_id = tenant_id
          @invoice_id = invoice_id
          @sort_by = sort_by
          @sort_order = sort_order
          @page = page
          @page_size = page_size
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @partner_id == other.partner_id
          return false unless @tenant_id == other.tenant_id
          return false unless @invoice_id == other.invoice_id
          return false unless @sort_by == other.sort_by
          return false unless @sort_order == other.sort_order
          return false unless @page == other.page
          return false unless @page_size == other.page_size
          true
        end
      end
    end
  end
end
