# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ListPartnersReferralFormData
        extend T::Sig
        include Crystalline::MetadataFields


        field :fields_, Crystalline::Array.new(Crystalline::Union.new(Models::Operations::ListPartnersFields1, Models::Operations::ListPartnersFields2, Models::Operations::ListPartnersFields3, Models::Operations::ListPartnersFields4, Models::Operations::Fields5, Models::Operations::Fields6, Models::Operations::Fields7, Models::Operations::Fields8)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('fields'), required: true } }

        sig { params(fields_: T::Array[T.any(Models::Operations::ListPartnersFields1, Models::Operations::ListPartnersFields2, Models::Operations::ListPartnersFields3, Models::Operations::ListPartnersFields4, Models::Operations::Fields5, Models::Operations::Fields6, Models::Operations::Fields7, Models::Operations::Fields8)]).void }
        def initialize(fields_:)
          @fields_ = fields_
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @fields_ == other.fields_
          true
        end
      end
    end
  end
end
