# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    
      # ListBountySubmissionsQueryParamSortOrder - The order to sort the submissions by.
      class ListBountySubmissionsQueryParamSortOrder < T::Enum


        enums do
          ASC = new('asc')
          DESC = new('desc')
        end
      end
    end
  end
end
