# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # ListPayoutsQueryParamSortBy - The field to sort the list of payouts by.
      class ListPayoutsQueryParamSortBy < T::Enum


        enums do
          AMOUNT = new('amount')
          INITIATED_AT = new('initiatedAt')
          PAID_AT = new('paidAt')
        end
      end
    end
  end
end
