# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ListPayoutsPartner
        extend T::Sig
        include Crystalline::MetadataFields

        # The partner's unique ID on Dub.
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # The partner's full legal name.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }
        # The partner's email address. Should be a unique value across Dub.
        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email'), required: true } }
        # The partner's avatar image.
        field :image, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('image'), required: true } }
        # The date when the partner enabled payouts.
        field :payouts_enabled_at, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('payoutsEnabledAt'), required: true } }
        # The partner's country (required for tax purposes).
        field :country, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('country'), required: true } }
        # The partner's unique ID within your database. Can be useful for associating the partner with a user in your database and retrieving/update their data in the future.
        field :tenant_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tenantId'), required: true } }
        # The partner's group ID on Dub.
        field :group_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('groupId') } }

        sig { params(id: ::String, name: ::String, email: T.nilable(::String), image: T.nilable(::String), payouts_enabled_at: T.nilable(::String), country: T.nilable(::String), tenant_id: T.nilable(::String), group_id: T.nilable(::String)).void }
        def initialize(id:, name:, email: nil, image: nil, payouts_enabled_at: nil, country: nil, tenant_id: nil, group_id: nil)
          @id = id
          @name = name
          @email = email
          @image = image
          @payouts_enabled_at = payouts_enabled_at
          @country = country
          @tenant_id = tenant_id
          @group_id = group_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @email == other.email
          return false unless @image == other.image
          return false unless @payouts_enabled_at == other.payouts_enabled_at
          return false unless @country == other.country
          return false unless @tenant_id == other.tenant_id
          return false unless @group_id == other.group_id
          true
        end
      end
    end
  end
end
