# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # ListPartnersQueryParamStatus - A filter on the list based on the partner's `status` field.
    class ListPartnersQueryParamStatus < T::Enum
      enums do
        PENDING = new('pending')
        APPROVED = new('approved')
        REJECTED = new('rejected')
        INVITED = new('invited')
        DECLINED = new('declined')
        BANNED = new('banned')
        ARCHIVED = new('archived')
      end
    end
  end
end
