# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # ListBountySubmissionsStatus - The status of the submission
      class ListBountySubmissionsStatus < T::Enum
        enums do
          DRAFT = new('draft')
          SUBMITTED = new('submitted')
          APPROVED = new('approved')
          REJECTED = new('rejected')
        end
      end
    end
  end
end
