# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # ListPayoutsQueryParamStatus - Filter the list of payouts by their corresponding status.
      class ListPayoutsQueryParamStatus < T::Enum
        enums do
          PENDING = new('pending')
          PROCESSING = new('processing')
          PROCESSED = new('processed')
          SENT = new('sent')
          COMPLETED = new('completed')
          FAILED = new('failed')
          CANCELED = new('canceled')
        end
      end
    end
  end
end
