# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # ListPartnersBannedReason - If the partner was banned from the program, this is the reason for the ban.
      class ListPartnersBannedReason < T::Enum


        enums do
          TOS_VIOLATION = new('tos_violation')
          INAPPROPRIATE_CONTENT = new('inappropriate_content')
          FAKE_TRAFFIC = new('fake_traffic')
          FRAUD = new('fraud')
          SPAM = new('spam')
          BRAND_ABUSE = new('brand_abuse')
        end
      end
    end
  end
end
