# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ListPayoutsStatus < T::Enum
        enums do
          PENDING = new('pending')
          PROCESSING = new('processing')
          PROCESSED = new('processed')
          SENT = new('sent')
          COMPLETED = new('completed')
          FAILED = new('failed')
          CANCELED = new('canceled')
        end
      end
    end
  end
end
