# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ListPartnersFieldsPartnersResponse200Type < T::Enum


        enums do
          COUNTRY = new('country')
        end
      end
    end
  end
end
