# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class Method < T::Enum
        enums do
          CONNECT = new('connect')
          STABLECOIN = new('stablecoin')
          PAYPAL = new('paypal')
          TREMENDOUS = new('tremendous')
        end
      end
    end
  end
end
