# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Partner < ::Crystalline::FieldAugmented
      extend T::Sig

      # The partner's email address. Partners will be able to claim their profile by signing up at `partners.dub.co` with this email.
      field :email, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }
      # The partner's country of residence. Must be passed as a 2-letter ISO 3166-1 country code. Learn more: https://d.to/geo
      field :country, T.nilable(::OpenApiSDK::Operations::CreateReferralsEmbedTokenCountry), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('country'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::CreateReferralsEmbedTokenCountry, true) } }
      # A brief description of the partner and their background. Max 5,000 characters.
      field :description, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('description') } }
      # The partner's avatar image. If not provided, a default avatar will be used.
      field :image, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('image') } }
      # Additional properties that you can pass to the partner's short link. Will be used to override the default link properties for this partner.
      field :link_props, T.nilable(::OpenApiSDK::Operations::CreateReferralsEmbedTokenLinkProps), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('linkProps') } }
      # The partner's full name. If undefined, the partner's email will be used in lieu of their name (e.g. `john@acme.com`)
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
      # The partner's unique ID in your system. Useful for retrieving the partner's links and stats later on. If not provided, the partner will be created as a standalone partner.
      field :tenant_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('tenantId') } }
      # The partner's unique username in your system (max 100 characters). This will be used to create a short link for the partner using your program's default domain. If not provided, Dub will try to generate a username from the partner's name or email.
      field :username, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('username') } }


      sig { params(email: ::String, country: T.nilable(::OpenApiSDK::Operations::CreateReferralsEmbedTokenCountry), description: T.nilable(::String), image: T.nilable(::String), link_props: T.nilable(::OpenApiSDK::Operations::CreateReferralsEmbedTokenLinkProps), name: T.nilable(::String), tenant_id: T.nilable(::String), username: T.nilable(::String)).void }
      def initialize(email: nil, country: nil, description: nil, image: nil, link_props: nil, name: nil, tenant_id: nil, username: nil)
        @email = email
        @country = country
        @description = description
        @image = image
        @link_props = link_props
        @name = name
        @tenant_id = tenant_id
        @username = username
      end
    end
  end
end
