# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # ProfileType - The partner's profile type on Dub.
      class ProfileType < T::Enum


        enums do
          INDIVIDUAL = new('individual')
          COMPANY = new('company')
        end
      end
    end
  end
end
