# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    
      # QueryParamGroupBy - The parameter to group the analytics data points by. Defaults to `count` if undefined.
      class QueryParamGroupBy < T::Enum


        enums do
          COUNT = new('count')
          TIMESERIES = new('timeseries')
          CONTINENTS = new('continents')
          REGIONS = new('regions')
          COUNTRIES = new('countries')
          CITIES = new('cities')
          DEVICES = new('devices')
          BROWSERS = new('browsers')
          OS = new('os')
          TRIGGER = new('trigger')
          TRIGGERS = new('triggers')
          REFERERS = new('referers')
          REFERER_URLS = new('referer_urls')
          TOP_FOLDERS = new('top_folders')
          TOP_LINK_TAGS = new('top_link_tags')
          TOP_DOMAINS = new('top_domains')
          TOP_LINKS = new('top_links')
          TOP_URLS = new('top_urls')
          TOP_PARTNERS = new('top_partners')
          UTM_SOURCES = new('utm_sources')
          UTM_MEDIUMS = new('utm_mediums')
          UTM_CAMPAIGNS = new('utm_campaigns')
          UTM_TERMS = new('utm_terms')
          UTM_CONTENTS = new('utm_contents')
        end
      end
    end
  end
end
