# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # QueryParamSortBy - The field to sort the tags by.
      class QueryParamSortBy < T::Enum
        enums do
          NAME = new('name')
          CREATED_AT = new('createdAt')
        end
      end
    end
  end
end
