# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # QueryParamSortBy - The field to sort the events by. The default is `timestamp`.
    class QueryParamSortBy < T::Enum
      enums do
        TIMESTAMP = new('timestamp')
      end
    end
  end
end
