# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # QueryParamInterval - The interval to retrieve analytics for. If undefined, defaults to 24h.
      class QueryParamInterval < T::Enum


        enums do
          TWENTY_FOURH = new('24h')
          SEVEND = new('7d')
          THIRTYD = new('30d')
          NINETYD = new('90d')
          ONEY = new('1y')
          MTD = new('mtd')
          QTD = new('qtd')
          YTD = new('ytd')
          ALL = new('all')
        end
      end
    end
  end
end
