# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # QueryParamStatus - Filter applications by status. One of `pending`, `approved`, or `rejected`. Defaults to `pending`.
      class QueryParamStatus < T::Enum
        enums do
          PENDING = new('pending')
          APPROVED = new('approved')
          REJECTED = new('rejected')
        end
      end
    end
  end
end
