# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations

      class ReferralFormData
        extend T::Sig
        include Crystalline::MetadataFields


        field :fields_, Crystalline::Array.new(Crystalline::Union.new(Models::Operations::Fields1, Models::Operations::Fields2, Models::Operations::Fields3, Models::Operations::Fields4, Models::Operations::Five, Models::Operations::Six, Models::Operations::Seven, Models::Operations::Eight)), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('fields'), required: true } }

        sig { params(fields_: T::Array[T.any(Models::Operations::Fields1, Models::Operations::Fields2, Models::Operations::Fields3, Models::Operations::Fields4, Models::Operations::Five, Models::Operations::Six, Models::Operations::Seven, Models::Operations::Eight)]).void }
        def initialize(fields_:)
          @fields_ = fields_
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @fields_ == other.fields_
          true
        end
      end
    end
  end
end
