# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class RegisterDomainRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The domain to claim. We only support .link domains for now.
        field :domain, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('domain'), required: true } }

        sig { params(domain: ::String).void }
        def initialize(domain:)
          @domain = domain
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @domain == other.domain
          true
        end
      end
    end
  end
end
