# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class RejectBountySubmissionRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :bounty_id, ::String, { 'path_param': { 'field_name': 'bountyId', 'style': 'simple', 'explode': false } }

        field :submission_id, ::String, { 'path_param': { 'field_name': 'submissionId', 'style': 'simple', 'explode': false } }

        field :request_body, Crystalline::Nilable.new(Models::Operations::RejectBountySubmissionRequestBody), { 'request': { 'media_type': 'application/json' } }

        sig { params(bounty_id: ::String, submission_id: ::String, request_body: T.nilable(Models::Operations::RejectBountySubmissionRequestBody)).void }
        def initialize(bounty_id:, submission_id:, request_body: nil)
          @bounty_id = bounty_id
          @submission_id = submission_id
          @request_body = request_body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @bounty_id == other.bounty_id
          return false unless @submission_id == other.submission_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
