# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # RequestBodyPaymentProcessor - The payment processor via which the sale was made.
      class RequestBodyPaymentProcessor < T::Enum
        enums do
          STRIPE = new('stripe')
          SHOPIFY = new('shopify')
          POLAR = new('polar')
          PADDLE = new('paddle')
          APPLE = new('apple')
          REVENUECAT = new('revenuecat')
          LEMONSQUEEZY = new('lemonsqueezy')
          DUB = new('dub')
          CUSTOM = new('custom')
        end
      end
    end
  end
end
