# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class RetrieveLinksRequest < ::Crystalline::FieldAugmented
      extend T::Sig


      field :program_id, ::String, { 'query_param': { 'field_name': 'programId', 'style': 'form', 'explode': true } }

      field :partner_id, T.nilable(::String), { 'query_param': { 'field_name': 'partnerId', 'style': 'form', 'explode': true } }

      field :tenant_id, T.nilable(::String), { 'query_param': { 'field_name': 'tenantId', 'style': 'form', 'explode': true } }


      sig { params(program_id: ::String, partner_id: T.nilable(::String), tenant_id: T.nilable(::String)).void }
      def initialize(program_id: nil, partner_id: nil, tenant_id: nil)
        @program_id = program_id
        @partner_id = partner_id
        @tenant_id = tenant_id
      end
    end
  end
end
