# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  
    # Sort - The field to sort the links by. The default is `createdAt`, and sort order is always descending.
    class Sort < T::Enum
      enums do
        CREATED_AT = new('createdAt')
        CLICKS = new('clicks')
        LAST_CLICKED = new('lastClicked')
      end
    end
  end
end
