# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # Status - Useful for marking a commission as pending, refunded, duplicate, canceled, or fraudulent. Takes precedence over `saleAmount` and `modifySaleAmount`. When a commission is marked as pending, refunded, duplicate, canceled, or fraudulent, it will be omitted from the payout, and the payout amount will be recalculated accordingly. Paid commissions cannot be updated.
      class Status < T::Enum
        enums do
          PENDING = new('pending')
          REFUNDED = new('refunded')
          DUPLICATE = new('duplicate')
          CANCELED = new('canceled')
          FRAUD = new('fraud')
        end
      end
    end
  end
end
