# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class TrackSaleRequestBody < ::OpenApiSDK::Utils::FieldAugmented
      extend T::Sig

      # The amount of the sale. Should be passed in cents.
      field :amount, ::Integer, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('amount') } }
      # This is the unique identifier for the customer in the client's app. This is used to track the customer's journey.
      field :customer_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('customerId') } }
      # The payment processor via which the sale was made.
      field :payment_processor, ::OpenApiSDK::Operations::PaymentProcessor, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('paymentProcessor'), 'decoder': Utils.enum_from_string(::OpenApiSDK::Operations::PaymentProcessor, false) } }
      # The currency of the sale. Accepts ISO 4217 currency codes.
      field :currency, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('currency') } }
      # The invoice ID of the sale.
      field :invoice_id, T.nilable(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('invoiceId') } }
      # Additional metadata to be stored with the sale event.
      field :metadata, T.nilable(T::Hash[Symbol, ::Object]), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('metadata') } }


      sig { params(amount: ::Integer, customer_id: ::String, payment_processor: ::OpenApiSDK::Operations::PaymentProcessor, currency: T.nilable(::String), invoice_id: T.nilable(::String), metadata: T.nilable(T::Hash[Symbol, ::Object])).void }
      def initialize(amount: nil, customer_id: nil, payment_processor: nil, currency: nil, invoice_id: nil, metadata: nil)
        @amount = amount
        @customer_id = customer_id
        @payment_processor = payment_processor
        @currency = currency
        @invoice_id = invoice_id
        @metadata = metadata
      end
    end
  end
end
