# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Operations
  

    class Type < T::Enum
      enums do
        PERCENTAGE = new('percentage')
        FLAT = new('flat')
      end
    end
  end
end
