# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdateCustomerRequestBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The customer's unique identifier your database. This is useful for associating subsequent conversion events from Dub's API to your internal systems.
        field :external_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('externalId') } }
        # The customer's country in ISO 3166-1 alpha-2 format. Updating this field will only affect the customer's country in Dub's system (and has no effect on existing conversion events).
        field :country, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('country') } }
        # The customer's email address.
        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }
        # The customer's name. If not provided, the email address will be used, and if email is not provided, a random name will be generated.
        field :name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name') } }
        # The customer's avatar URL. If not provided, a random avatar will be generated.
        field :avatar, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('avatar') } }
        # The customer's Stripe customer ID. This is useful for attributing recurring sale events to the partner who referred the customer.
        field :stripe_customer_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('stripeCustomerId') } }

        sig { params(external_id: T.nilable(::String), country: T.nilable(::String), email: T.nilable(::String), name: T.nilable(::String), avatar: T.nilable(::String), stripe_customer_id: T.nilable(::String)).void }
        def initialize(external_id: nil, country: nil, email: nil, name: nil, avatar: nil, stripe_customer_id: nil)
          @external_id = external_id
          @country = country
          @email = email
          @name = name
          @avatar = avatar
          @stripe_customer_id = stripe_customer_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @external_id == other.external_id
          return false unless @country == other.country
          return false unless @email == other.email
          return false unless @name == other.name
          return false unless @avatar == other.avatar
          return false unless @stripe_customer_id == other.stripe_customer_id
          true
        end
      end
    end
  end
end
