# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
      # The customer was updated.
      class UpdateCustomerResponseBody
        extend T::Sig
        include Crystalline::MetadataFields

        # The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
        field :id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('id'), required: true } }
        # Name of the customer.
        field :name, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('name'), required: true } }
        # Unique identifier for the customer in the client's app.
        field :external_id, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('externalId'), required: true } }
        # The date the customer was created (usually the signup date or trial start date).
        field :created_at, ::String, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('createdAt'), required: true } }
        # Email of the customer.
        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('email') } }
        # Avatar URL of the customer.
        field :avatar, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('avatar') } }
        # The customer's Stripe customer ID. This is useful for attributing recurring sale events to the partner who referred the customer.
        field :stripe_customer_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('stripeCustomerId') } }
        # Country of the customer.
        field :country, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('country') } }
        # Total number of sales for the customer.
        field :sales, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('sales') } }
        # Total amount of sales for the customer.
        field :sale_amount, Crystalline::Nilable.new(::Float), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('saleAmount') } }
        # The date the customer made their first sale. Useful for calculating the time to first sale and LTV.
        field :first_sale_at, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('firstSaleAt') } }
        # The date the customer canceled their subscription. Useful for calculating LTV and churn rate.
        field :subscription_canceled_at, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('subscriptionCanceledAt') } }

        field :link, Crystalline::Nilable.new(Models::Operations::UpdateCustomerLink), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('link') } }

        field :program_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('programId') } }

        field :partner, Crystalline::Nilable.new(Models::Operations::UpdateCustomerPartner), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('partner') } }

        field :discount, Crystalline::Nilable.new(Models::Operations::UpdateCustomerDiscount), { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('discount') } }

        sig { params(id: ::String, name: ::String, external_id: ::String, created_at: ::String, email: T.nilable(::String), avatar: T.nilable(::String), stripe_customer_id: T.nilable(::String), country: T.nilable(::String), sales: T.nilable(::Float), sale_amount: T.nilable(::Float), first_sale_at: T.nilable(::String), subscription_canceled_at: T.nilable(::String), link: T.nilable(Models::Operations::UpdateCustomerLink), program_id: T.nilable(::String), partner: T.nilable(Models::Operations::UpdateCustomerPartner), discount: T.nilable(Models::Operations::UpdateCustomerDiscount)).void }
        def initialize(id:, name:, external_id:, created_at:, email: nil, avatar: nil, stripe_customer_id: nil, country: nil, sales: nil, sale_amount: nil, first_sale_at: nil, subscription_canceled_at: nil, link: nil, program_id: nil, partner: nil, discount: nil)
          @id = id
          @name = name
          @external_id = external_id
          @created_at = created_at
          @email = email
          @avatar = avatar
          @stripe_customer_id = stripe_customer_id
          @country = country
          @sales = sales
          @sale_amount = sale_amount
          @first_sale_at = first_sale_at
          @subscription_canceled_at = subscription_canceled_at
          @link = link
          @program_id = program_id
          @partner = partner
          @discount = discount
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @id == other.id
          return false unless @name == other.name
          return false unless @external_id == other.external_id
          return false unless @created_at == other.created_at
          return false unless @email == other.email
          return false unless @avatar == other.avatar
          return false unless @stripe_customer_id == other.stripe_customer_id
          return false unless @country == other.country
          return false unless @sales == other.sales
          return false unless @sale_amount == other.sale_amount
          return false unless @first_sale_at == other.first_sale_at
          return false unless @subscription_canceled_at == other.subscription_canceled_at
          return false unless @link == other.link
          return false unless @program_id == other.program_id
          return false unless @partner == other.partner
          return false unless @discount == other.discount
          true
        end
      end
    end
  end
end
