# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Operations
    

      class UpdateLinkRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The id of the link to update. You may use either `linkId` (obtained via `/links/info` endpoint) or `externalId` prefixed with `ext_`.
        field :link_id, ::String, { 'path_param': { 'field_name': 'linkId', 'style': 'simple', 'explode': false } }

        field :request_body, Crystalline::Nilable.new(Models::Operations::UpdateLinkRequestBody), { 'request': { 'media_type': 'application/json' } }

        sig { params(link_id: ::String, request_body: T.nilable(Models::Operations::UpdateLinkRequestBody)).void }
        def initialize(link_id:, request_body: nil)
          @link_id = link_id
          @request_body = request_body
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @link_id == other.link_id
          return false unless @request_body == other.request_body
          true
        end
      end
    end
  end
end
