# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Errors
    
      # The user has sent too many requests in a given amount of time ("rate limiting")
      class RateLimitExceeded
        extend T::Sig
        include Crystalline::MetadataFields


        field :error, Models::Errors::RateLimitExceededError, { 'format_json': { 'letter_case': ::OpenApiSDK::Utils.field_name('error'), required: true } }

        sig { params(error: Models::Errors::RateLimitExceededError).void }
        def initialize(error:)
          @error = error
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @error == other.error
          true
        end
      end
    end
  end
end
