# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
# Generated under the AGPL-3.0-only license.
# SPDX-License-Identifier: AGPL-3.0-only

# typed: true
# frozen_string_literal: true


module OpenApiSDK
  module Models
    module Errors
      # UnauthorizedCode - A short code indicating the error code returned.
      class UnauthorizedCode < T::Enum
        enums do
          UNAUTHORIZED = new('unauthorized')
        end
      end
    end
  end
end
